import "server-only";

import type { TokenBundle } from "@/services/social-connections/x-oauth";
import { VerificationFailureError } from "@/services/verification";

/**
 * TikTok Login Kit — OAuth Authorization Code flow (official APIs only).
 *
 * Endpoints (developers.tiktok.com, verified against current docs):
 *   authorize:  https://www.tiktok.com/v2/auth/authorize/
 *   token:      https://open.tiktokapis.com/v2/oauth/token/   (POST, form-encoded)
 *   identity:   https://open.tiktokapis.com/v2/user/info/     (GET/POST, user token)
 *
 * TikTok requires PKCE for web flows too (code_challenge + code_verifier on
 * both authorize and token requests). The token response returns open_id —
 * the TikTok user's unique identifier, which becomes our platformUserId —
 * plus short-lived user access tokens (24h) refreshed with a long-lived
 * refresh token (365d). The access token is exactly what the Stage 6
 * video.query verifier needs, so connecting an account is what finally
 * unblocks TikTok verification for that creator.
 *
 * The client secret never leaves the server; nothing here is importable from
 * client code ("server-only").
 */

const TIKTOK_AUTHORIZE_URL = "https://www.tiktok.com/v2/auth/authorize/";
const TIKTOK_TOKEN_URL = "https://open.tiktokapis.com/v2/oauth/token/";
const TIKTOK_USER_INFO_URL = "https://open.tiktokapis.com/v2/user/info/";

/**
 * Minimum scopes: identity (user.info.basic) + video.list, which the existing
 * video.query verifier requires. Nothing beyond what verification needs.
 */
export const TIKTOK_OAUTH_SCOPES = ["user.info.basic", "video.list"] as const;

const REQUEST_TIMEOUT_MS = 10_000;

export type TikTokOAuthConfig = {
  clientKey: string;
  clientSecret: string;
  redirectUri: string;
};

export function resolveTikTokOAuthConfig(): TikTokOAuthConfig | null {
  const clientKey = process.env.TIKTOK_CLIENT_KEY;
  const clientSecret = process.env.TIKTOK_CLIENT_SECRET;
  const redirectUri =
    process.env.TIKTOK_REDIRECT_URI ??
    (process.env.APP_BASE_URL
      ? `${process.env.APP_BASE_URL.replace(/\/+$/, "")}/api/auth/callback/tiktok`
      : undefined);

  if (!clientKey || !clientSecret || !redirectUri) {
    return null;
  }

  return { clientKey, clientSecret, redirectUri };
}

/**
 * Build the TikTok authorize URL. The verifier + state are generated by the
 * caller and must be persisted server-side before redirecting.
 */
export function buildTikTokAuthorizeUrl(
  state: string,
  options: { codeVerifier: string },
): string {
  const config = resolveTikTokOAuthConfig();

  if (!config) {
    throw new Error("TikTok OAuth is not configured on this server.");
  }

  const codeChallenge = derivePkceChallengePublic(options.codeVerifier);

  const params = new URLSearchParams({
    client_key: config.clientKey,
    scope: TIKTOK_OAUTH_SCOPES.join(","),
    response_type: "code",
    redirect_uri: config.redirectUri,
    state,
    code_challenge: codeChallenge,
    code_challenge_method: "S256",
  });

  return `${TIKTOK_AUTHORIZE_URL}?${params.toString()}`;
}

// Local re-export shim so the module does not import "server-only" neighbor
// twice; keeps the pure PKCE derivation one import away from tests.
import { derivePkceChallenge as derivePkceChallengePublic } from "@/lib/oauth-flow";

type TikTokTokenResponse = {
  access_token?: string;
  expires_in?: number;
  refresh_token?: string;
  refresh_expires_in?: number;
  scope?: string;
  open_id?: string;
  token_type?: string;
  error?: { code?: string; message?: string };
};

export type TikTokIdentity = {
  platformUserId: string;
  platformUsername: string | null;
  displayName: string | null;
};

/**
 * Exchange the authorization code for tokens and resolve the connected
 * TikTok identity. open_id comes from the token response itself; the user
 * info endpoint enriches the display handle (best-effort — a failure there
 * downgrades to open_id-based display, it does not fail the connection).
 */
export async function exchangeTikTokCodeForIdentity(
  code: string,
  codeVerifier: string,
): Promise<{ identity: TikTokIdentity; tokens: TokenBundle }> {
  const config = resolveTikTokOAuthConfig();

  if (!config) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok OAuth is not configured on this server.",
    );
  }

  const body = new URLSearchParams({
    client_key: config.clientKey,
    client_secret: config.clientSecret,
    code,
    grant_type: "authorization_code",
    redirect_uri: config.redirectUri,
    code_verifier: codeVerifier,
  });

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let tokenResponse: Response;

  try {
    tokenResponse = await fetch(TIKTOK_TOKEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: body.toString(),
      signal: controller.signal,
      cache: "no-store",
    });
  } catch {
    throw new VerificationFailureError(
      "PROVIDER_UNAVAILABLE",
      "Could not reach the TikTok token endpoint.",
    );
  } finally {
    clearTimeout(timeout);
  }

  if (!tokenResponse.ok) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok rejected the authorization code exchange.",
    );
  }

  const payload = (await tokenResponse.json()) as TikTokTokenResponse;

  if (payload.error && payload.error.code && payload.error.code !== "ok") {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      payload.error.message ?? "TikTok rejected the authorization code exchange.",
    );
  }

  if (!payload.access_token || !payload.open_id) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok did not return an access token and identity.",
    );
  }

  const identity = await fetchTikTokIdentity(
    payload.access_token,
    payload.open_id,
  );

  return {
    identity,
    tokens: {
      accessToken: payload.access_token,
      refreshToken: payload.refresh_token ?? null,
      accessTokenExpiresAt: payload.expires_in
        ? new Date(Date.now() + payload.expires_in * 1000)
        : null,
      refreshTokenExpiresAt: payload.refresh_expires_in
        ? new Date(Date.now() + payload.refresh_expires_in * 1000)
        : null,
      grantedScopes: payload.scope ?? null,
    },
  };
}

type TikTokUserInfoResponse = {
  data?: {
    user?: {
      open_id?: string;
      union_id?: string;
      display_name?: string;
      username?: string;
      avatar_url?: string;
    };
  };
  error?: { code?: string; message?: string };
};

async function fetchTikTokIdentity(
  accessToken: string,
  openId: string,
): Promise<TikTokIdentity> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let response: Response;

  try {
    response = await fetch(
      `${TIKTOK_USER_INFO_URL}?fields=open_id,display_name,username`,
      {
        headers: { Authorization: `Bearer ${accessToken}` },
        signal: controller.signal,
        cache: "no-store",
      },
    );
  } catch {
    // Identity enrichment is best-effort; open_id from the token response is
    // the authoritative identity either way.
    return { platformUserId: openId, platformUsername: null, displayName: null };
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    return { platformUserId: openId, platformUsername: null, displayName: null };
  }

  const payload = (await response.json()) as TikTokUserInfoResponse;
  const user = payload.data?.user;

  return {
    platformUserId: user?.open_id ?? openId,
    platformUsername: user?.username ?? null,
    displayName: user?.display_name ?? null,
  };
}

/**
 * Refresh a TikTok user access token with the stored refresh token (Stage 11).
 * TikTok rotates refresh tokens on each use — the response's new
 * refresh_token replaces the stored one.
 */
export async function refreshTikTokAccessToken(
  refreshToken: string,
): Promise<TokenBundle> {
  const config = resolveTikTokOAuthConfig();

  if (!config) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok OAuth is not configured on this server.",
    );
  }

  const body = new URLSearchParams({
    client_key: config.clientKey,
    client_secret: config.clientSecret,
    grant_type: "refresh_token",
    refresh_token: refreshToken,
  });

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let response: Response;

  try {
    response = await fetch(TIKTOK_TOKEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: body.toString(),
      signal: controller.signal,
      cache: "no-store",
    });
  } catch {
    throw new VerificationFailureError(
      "PROVIDER_UNAVAILABLE",
      "Could not reach the TikTok token endpoint.",
    );
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok rejected the token refresh.",
    );
  }

  const payload = (await response.json()) as TikTokTokenResponse;

  if (payload.error && payload.error.code && payload.error.code !== "ok") {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok rejected the token refresh.",
    );
  }

  if (!payload.access_token) {
    throw new VerificationFailureError(
      "PROVIDER_AUTH",
      "TikTok did not return an access token.",
    );
  }

  return {
    accessToken: payload.access_token,
    refreshToken: payload.refresh_token ?? refreshToken,
    accessTokenExpiresAt: payload.expires_in
      ? new Date(Date.now() + payload.expires_in * 1000)
      : null,
    refreshTokenExpiresAt: payload.refresh_expires_in
      ? new Date(Date.now() + payload.refresh_expires_in * 1000)
      : null,
    grantedScopes: payload.scope ?? null,
  };
}

/**
 * Revoke a TikTok user token (Stage 11 disconnect). Best-effort: failures
 * are logged with a status code only and never block the local disconnect —
 * the local credentials are deleted regardless.
 * https://open.tiktokapis.com/v2/oauth/revoke/
 */
export async function revokeTikTokToken(token: string): Promise<boolean> {
  const config = resolveTikTokOAuthConfig();

  if (!config) {
    return false;
  }

  try {
    const response = await fetch("https://open.tiktokapis.com/v2/oauth/revoke/", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_key: config.clientKey,
        client_secret: config.clientSecret,
        token,
      }).toString(),
      cache: "no-store",
    });

    return response.ok;
  } catch {
    return false;
  }
}
